/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by the @tanstack/router-plugin
// File-based routing setup - actual route tree will be generated on dev/build

import { createRootRoute, createFileRoute } from '@tanstack/react-router'

type FileRoutesByTo = {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexImport
    parentRoute: typeof RootRoute
  }
  '/login': {
    id: '/login'
    path: '/login'
    fullPath: '/login'
    preLoaderRoute: typeof LoginImport
    parentRoute: typeof RootRoute
  }
  '/signup': {
    id: '/signup'
    path: '/signup'
    fullPath: '/signup'
    preLoaderRoute: typeof SignupImport
    parentRoute: typeof RootRoute
  }
  '/_auth': {
    id: '/_auth'
    path: '/_auth'
    fullPath: '/_auth'
    preLoaderRoute: typeof AuthLayoutImport
    parentRoute: typeof RootRoute
  }
  '/_auth/dashboard': {
    id: '/_auth/dashboard'
    path: '/dashboard'
    fullPath: '/_auth/dashboard'
    preLoaderRoute: typeof DashboardImport
    parentRoute: typeof AuthLayoutImport
  }
}

const RootRoute = createRootRoute()
const IndexImport = { __isFileRoute: true }
const LoginImport = { __isFileRoute: true }
const SignupImport = { __isFileRoute: true }
const AuthLayoutImport = { __isFileRoute: true }
const DashboardImport = { __isFileRoute: true }

export const routeTree = RootRoute.addChildren([
  IndexImport,
  LoginImport,
  SignupImport,
  AuthLayoutImport.addChildren([DashboardImport]),
]) as any

export type RootRouteTree = typeof routeTree
